backend:
  name: git-gateway
  branch: main

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "guide"
    label: "Guide"
    folder: "docs/guide"
    create: true
    preview_path: "/guide/{{fields.path_folder}}/{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Dossier", name: "path_folder", widget: "string", hint: "Ex: frontend/vuejs (pas de slash à la fin)", required: true }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Corps", name: "body", widget: "markdown" }
      - {
          label: "Chemin du fichier",
          name: "path",
          widget: "hidden",
          default: "{{fields.path_folder}}/{{slug}}"
        }
    path: "{{fields.path_folder}}/{{slug}}"
    slug: "{{slug}}"