backend:
  name: git-gateway
  branch: main

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "guide"
    label: "Guide"
    folder: "docs/guide"
    create: true
    slug: "{{slug}}"
    path: "{{fields.path_folder | trim_slashes}}/{{slug}}"
    preview_path: "/guide/{{fields.path_folder}}/{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Chemin du dossier"
        name: "path_folder"
        widget: "string"
        hint: "Ex : frontend/vuejs ou backend/express. Ne pas mettre de slash au début ou à la fin."
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Corps", name: "body", widget: "markdown" }
