backend:
  name: git-gateway
  branch: main

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "guide"
    label: "Guide"
    folder: "docs/guide"
    create: true
    slug: "{{fields.full_path}}"  # Le slug contient tout le chemin relatif + slug final
    preview_path: "/guide/{{fields.full_path}}"
    editor:
      preview: false
    fields:
      - {
          label: "Chemin complet (dossier/slug)",
          name: "full_path",
          widget: "string",
          hint: "Ex: backend/express/mon-guide (pas d’extension .md, pas de slash au début)"
        }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Corps", name: "body", widget: "markdown" }

