backend:
  name: git-gateway
  branch: main

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "guide"
    label: "Guide"
    label_singular: "Article"
    folder: "docs/guide"
    create: true
    slug: "{{slug}}"
    preview_path: "/guide/{{fields.category}}/{{slug}}"
    nested:
      depth: 100
      subfolder: "false"
      summary: '{{title}}'
    editor:
      preview: false
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Catégorie", name: "category", widget: "select", options: ["frontend", "backend", "design"] }
      - { label: "Corps", name: "body", widget: "markdown" }
    meta:
      path:
        widget: string
        label: 'Chemin du fichier (ex: sous-dossier/mon-article)'
        index_file: 'index'
