backend:
  name: git-gateway
  branch: main

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "guide"
    label: "Guide"
    folder: "docs/guide"
    create: true
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' 
    slug: "{{slug}}"
    preview_path: "/guide/{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Corps", name: "body", widget: "markdown" }
      - { label: "Chemin du fichier", name: "path", widget: "hidden", default: "{{slug}}" }

  # Exemple d'une collection avec sous-dossiers
