backend:
  name: git-gateway
  branch: main

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "guide"
    label: "Guide"
    folder: "docs/guide"
    create: true
    slug: "{{fields.path_folder}}{{slug}}"  # On injecte ici le chemin complet
    preview_path: "/guide/{{fields.path_folder}}/{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Chemin du dossier"
        name: "path_folder"
        widget: "string"
        hint: "Ex: frontend/vuejs — ne commence ni ne termine par un slash"
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Corps", name: "body", widget: "markdown" }
